/** React renderer entrypoint for the media-library workspace. */
import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Archive, Check, ChevronLeft, ChevronRight, Database, FolderOpen, HardDrive, Library, LoaderCircle, Play, RefreshCw, Search, Settings2, ShieldAlert, SlidersHorizontal, Terminal, X } from 'lucide-react';
import type { AppSettings, FilterState, FolderNode, OperationPlan, ProjectRecord, ProjectSource, ProjectType, TaskEvent } from '../shared/types.js';
import './styles.css';
import './extensions.css';
import './setup.css';

const emptyFilter: FilterState = { search: '', sources: [], types: [], showInvalid: true, sort: 'updatedAt', descending: true, page: 1, pageSize: 30, folderId: null };
const sourceLabels: Record<ProjectSource, string> = { workshop: '创意工坊', backup: '本地备份', temp: '临时目录', nas: 'NAS', unknown: '未知' };
const typeLabels: Record<ProjectType, string> = { scene: '场景', video: '视频', web: '网页', application: '应用', unknown: '其他' };
const fmtSize = (n: number) => n > 1024 ** 3 ? `${(n / 1024 ** 3).toFixed(1)} GB` : n > 1024 ** 2 ? `${(n / 1024 ** 2).toFixed(1)} MB` : `${Math.max(1, Math.round(n / 1024))} KB`;

function App() {
  const [settings, setSettings] = useState<AppSettings | null>(null); const [filter, setFilter] = useState(emptyFilter); const [items, setItems] = useState<ProjectRecord[]>([]); const [folders, setFolders] = useState<FolderNode[]>([]); const [total, setTotal] = useState(0); const [selected, setSelected] = useState<ProjectRecord | null>(null); const [events, setEvents] = useState<TaskEvent[]>([]); const [tab, setTab] = useState<'library' | 'repkg' | 'storage' | 'settings'>('library'); const [busy, setBusy] = useState(false); const [repkgPath, setRepkgPath] = useState('');
  const load = async () => { const page = await window.remake.library.list({ filter }); setItems(page.items); setTotal(page.total); if (selected) setSelected(await window.remake.library.get(selected.id)); };
  useEffect(() => { void window.remake.settings.get().then(setSettings); const off = window.remake.onTaskEvent((event) => { setEvents((old) => [event, ...old.filter((item) => item.taskId !== event.taskId)].slice(0, 8)); if (event.kind === 'scan' && event.status === 'completed') { void load(); void window.remake.library.folders().then(setFolders); } }); return off; }, []);
  useEffect(() => { if (settings) void load(); }, [settings, filter.search, filter.page, filter.pageSize, filter.sort, filter.descending, filter.showInvalid, filter.folderId, filter.sources.join(','), filter.types.join(',')]);
  const pageCount = Math.max(1, Math.ceil(total / filter.pageSize));
  const updateSettings = async (patch: Partial<AppSettings>) => { const next = await window.remake.settings.update(patch); setSettings(next); };
  const scan = async () => { setBusy(true); await window.remake.library.scan(); setBusy(false); };
  const toggle = <T extends string>(value: T, values: T[], setter: (value: T[]) => void) => setter(values.includes(value) ? values.filter((item) => item !== value) : [...values, value]);
  if (!settings) return <div className="loading"><LoaderCircle className="spin" />正在准备工作区…</div>;
  if (!settings.steamPath && !settings.wallpaperPath) return <SetupWizard onDone={setSettings} />;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><div className="brand-mark">W</div><div><strong>Wallpaper Tools</strong><span>个人媒体库</span></div></div><nav>{[['library', Library, '壁纸库'], ['repkg', Archive, 'RePKG 提取'], ['storage', HardDrive, '存储整理'], ['settings', Settings2, '设置']].map(([key, Icon, label]) => <button className={tab === key ? 'nav-item active' : 'nav-item'} onClick={() => setTab(key as typeof tab)} key={key as string}><Icon size={18} />{label as string}</button>)}</nav><div className="sidebar-bottom"><div className="health-dot" /><span>本地模式 · 数据不上传</span></div></aside>
    <main className="workspace"><header className="topbar"><div><p className="eyebrow">WALLPAPER ENGINE TOOLS</p><h1>{tab === 'library' ? '壁纸库' : tab === 'repkg' ? 'RePKG 提取' : tab === 'storage' ? '存储整理' : '设置'}</h1></div><div className="top-actions"><button className="ghost-button" onClick={() => void scan()} disabled={busy}><RefreshCw size={16} className={busy ? 'spin' : ''} />{busy ? '扫描中' : '重新扫描'}</button><button className="icon-button" title="诊断" onClick={async () => alert(JSON.stringify(await window.remake.diagnostics.getEnvironment(), null, 2))}><Terminal size={17} /></button></div></header>
      {tab === 'library' && <><section className="toolbar"><div className="search"><Search size={17} /><input value={filter.search} placeholder="搜索标题、ID 或描述" onChange={(e) => setFilter({ ...filter, search: e.target.value, page: 1 })} /></div><select value={filter.sort} onChange={(e) => setFilter({ ...filter, sort: e.target.value as FilterState['sort'] })}><option value="updatedAt">最近更新</option><option value="title">名称</option><option value="fileSize">文件大小</option><option value="subscriptionDate">订阅日期</option></select><button className={filter.descending ? 'chip active' : 'chip'} onClick={() => setFilter({ ...filter, descending: !filter.descending })}>{filter.descending ? '倒序' : '正序'}</button><button className={filter.showInvalid ? 'chip active' : 'chip'} onClick={() => setFilter({ ...filter, showInvalid: !filter.showInvalid })}><ShieldAlert size={14} />失效</button></section><div className="content-grid"><aside className="filters"><FilterSection title="来源"><FilterChecks values={['workshop', 'backup', 'temp', 'nas']} selected={filter.sources} labels={sourceLabels} onToggle={(v) => toggle(v, filter.sources, (sources) => setFilter({ ...filter, sources, page: 1 }))} /></FilterSection><FilterSection title="类型"><FilterChecks values={['scene', 'video', 'web', 'application']} selected={filter.types} labels={typeLabels} onToggle={(v) => toggle(v, filter.types, (types) => setFilter({ ...filter, types, page: 1 }))} /></FilterSection>{folders.length > 0 && <FilterSection title="分类"><FolderTree nodes={folders} selected={filter.folderId} onSelect={(folderId) => setFilter({ ...filter, folderId, page: 1 })} /></FilterSection>}<div className="filter-note"><SlidersHorizontal size={16} /><span>共 {total} 个项目</span></div></aside><section className="library-area"><div className="section-meta"><span>{total ? `${(filter.page - 1) * filter.pageSize + 1}-${Math.min(filter.page * filter.pageSize, total)} / ${total}` : '暂无索引'}</span><button className="text-button" onClick={() => setFilter(emptyFilter)}>重置筛选</button></div><div className="card-grid">{items.map((item) => <ProjectCard key={item.id} item={item} selected={selected?.id === item.id} onClick={() => setSelected(item)} />)}{!items.length && <div className="empty-state"><Database size={34} /><strong>还没有索引项目</strong><span>在设置中配置目录后，点击“重新扫描”开始建立媒体库。</span></div>}</div><div className="pagination"><button className="icon-button" disabled={filter.page <= 1} onClick={() => setFilter({ ...filter, page: filter.page - 1 })}><ChevronLeft size={17} /></button><span>第 {filter.page} / {pageCount} 页</span><button className="icon-button" disabled={filter.page >= pageCount} onClick={() => setFilter({ ...filter, page: filter.page + 1 })}><ChevronRight size={17} /></button></div></section><Details item={selected} onClose={() => setSelected(null)} /></div></>}
      {tab === 'repkg' && <RepkgPanel path={repkgPath} setPath={setRepkgPath} events={events} />}
      {tab === 'storage' && <StoragePanel settings={settings} updateSettings={updateSettings} selected={selected} />}
      {tab === 'settings' && <SettingsPanel settings={settings} updateSettings={updateSettings} />}
    </main></div>;
}

function SetupWizard({ onDone }: { onDone: (settings: AppSettings) => void }) {
  const [steam, setSteam] = useState(''); const [wallpaper, setWallpaper] = useState(''); const [backup, setBackup] = useState('');
  const detect = async () => { const found = await window.remake.settings.detectPaths(); setSteam(found.steamPath || ''); setWallpaper(found.wallpaperPath || ''); setBackup(found.backupPath || ''); };
  const finish = async () => onDone(await window.remake.settings.update({ steamPath: steam, wallpaperPath: wallpaper, backupPath: backup }));
  return <main className="setup"><div className="setup-panel"><div className="brand-mark">W</div><p className="eyebrow">首次设置</p><h1>连接你的壁纸库</h1><p className="setup-copy">配置只保存在重制版用户数据目录，旧版文件不会被读取或覆盖。</p><button className="ghost-button detect-button" onClick={() => void detect()}><RefreshCw size={15} />自动识别本机路径</button><label>Steam 目录<input value={steam} onChange={(e) => setSteam(e.target.value)} /></label><label>Wallpaper Engine 目录<input value={wallpaper} onChange={(e) => setWallpaper(e.target.value)} /></label><label>我的壁纸目录<input value={backup} onChange={(e) => setBackup(e.target.value)} /></label><button className="primary-button setup-finish" disabled={!steam && !wallpaper} onClick={() => void finish()}>进入壁纸库<ChevronRight size={16} /></button></div></main>;
}

function FilterSection({ title, children }: { title: string; children: React.ReactNode }) { return <section className="filter-section"><h3>{title}</h3>{children}</section>; }
function FilterChecks<T extends string>({ values, selected, labels, onToggle }: { values: T[]; selected: T[]; labels: Record<T, string>; onToggle: (value: T) => void }) { return <div className="check-list">{values.map((value) => <button className={selected.includes(value) ? 'check-row checked' : 'check-row'} key={value} onClick={() => onToggle(value)}><span className="check-box">{selected.includes(value) && <Check size={12} />}</span>{labels[value]}</button>)}</div>; }
function FolderTree({ nodes, selected, onSelect, depth = 0 }: { nodes: FolderNode[]; selected: string | null; onSelect: (id: string | null) => void; depth?: number }) { return <div className="folder-tree">{depth === 0 && <button className={!selected ? 'folder-row active' : 'folder-row'} onClick={() => onSelect(null)}>全部分类</button>}{nodes.map((node) => <React.Fragment key={node.id}><button className={selected === node.id ? 'folder-row active' : 'folder-row'} style={{ paddingLeft: 7 + depth * 12 }} onClick={() => onSelect(node.id)}>{node.title}</button>{node.children.length > 0 && <FolderTree nodes={node.children} selected={selected} onSelect={onSelect} depth={depth + 1} />}</React.Fragment>)}</div>; }
function Thumbnail({ path: previewPath, size = 24 }: { path: string | null; size?: number }) { const [source, setSource] = useState<string | null>(null); useEffect(() => { let active = true; setSource(null); if (previewPath) void window.remake.library.getThumbnail(previewPath).then((value) => { if (active) setSource(value); }); return () => { active = false; }; }, [previewPath]); return source ? <img src={source} /> : <div className="thumb-placeholder"><Library size={size} /></div>; }
function ProjectCard({ item, selected, onClick }: { item: ProjectRecord; selected: boolean; onClick: () => void }) { return <button className={selected ? 'project-card selected' : 'project-card'} onClick={onClick}><div className="thumb"><Thumbnail path={item.previewPath} />{item.invalid && <span className="invalid-badge">失效</span>}</div><div className="card-body"><strong title={item.title}>{item.title}</strong><div><span>{sourceLabels[item.source]}</span><span>{typeLabels[item.type]}</span></div><small>{fmtSize(item.fileSize)}</small></div></button>; }
function Details({ item, onClose }: { item: ProjectRecord | null; onClose: () => void }) { const [title, setTitle] = useState(item?.title || ''); const [size, setSize] = useState(item?.fileSize || 0); useEffect(() => { setTitle(item?.title || ''); setSize(item?.fileSize || 0); }, [item?.id]); if (!item) return <aside className="details empty-details"><FolderOpen size={28} /><span>选择一个项目查看详情</span></aside>; const save = async () => { await window.remake.library.updateMetadata(item.id, { title, description: item.description, favorite: item.favorite, tags: item.tags }); alert('项目元数据已保存'); }; const recalculate = async () => setSize((await window.remake.library.recalculateSize(item.id)).fileSize); return <aside className="details"><div className="details-head"><span>项目详情</span><button className="icon-button" onClick={onClose}><X size={16} /></button></div><div className="detail-preview"><Thumbnail path={item.previewPath} size={32} /></div><label>标题<input value={title} onChange={(e) => setTitle(e.target.value)} /></label><div className="detail-tags"><span>{sourceLabels[item.source]}</span><span>{typeLabels[item.type]}</span><span>{fmtSize(size)}</span></div><p className="description">{item.description || '暂无描述'}</p><div className="detail-actions"><button className="primary-button" onClick={() => void save()}><Check size={15} />保存修改</button><button className="ghost-button" onClick={() => void navigator.clipboard.writeText(item.title)}>复制标题</button><button className="ghost-button" onClick={() => void recalculate()}><RefreshCw size={15} />重新计算容量</button><button className="ghost-button" onClick={() => void window.remake.library.openPath(item.rootPath)}><FolderOpen size={15} />打开目录</button></div></aside>; }
function RepkgPanel({ path: inputPath, setPath, events }: { path: string; setPath: (v: string) => void; events: TaskEvent[] }) { const [jobId, setJobId] = useState<string | null>(null); const [files, setFiles] = useState<string[]>([]); const event = events.find((item) => item.taskId === jobId); const run = async () => { if (!inputPath) return; const next = await window.remake.repkg.start(inputPath); setJobId(next.id); }; const choose = async () => { const file = await window.remake.settings.pickFile([{ name: 'RePKG', extensions: ['pkg', 'mpkg'] }]); if (file) setPath(file); }; const refresh = async () => { if (jobId) setFiles(await window.remake.repkg.getOutput(jobId)); }; return <section className="tool-panel"><div className="panel-intro"><Archive size={20} /><div><h2>纹理提取</h2><p>每次任务使用独立输出目录，不会清理其他提取结果。</p></div></div><div className="path-row"><input value={inputPath} onChange={(e) => setPath(e.target.value)} placeholder="选择 .pkg 或 .mpkg 文件" /><button className="ghost-button" onClick={() => void choose()}><FolderOpen size={15} />选择</button><button className="primary-button" onClick={() => void run()} disabled={!inputPath}><Play size={15} />开始提取</button></div>{jobId && <div className="job-card"><div className="job-line"><span>{event?.status || '正在启动'}</span><div><button className="text-button" onClick={() => void refresh()}>刷新结果</button>{event?.status === 'running' && <button className="text-button danger" onClick={() => void window.remake.repkg.cancel(jobId)}>取消</button>}</div></div><div className="progress"><i style={{ width: `${event?.progress || 0}%` }} /></div>{files.length > 0 && <div className="output-list">{files.map((file) => <button className="file-result" key={file} onClick={() => void window.remake.library.openPath(file)}>{file}</button>)}</div>}</div>}<TaskLog events={events.filter((item) => item.kind === 'repkg')} /></section>; }
function StoragePanel({ settings, updateSettings, selected }: { settings: AppSettings; updateSettings: (patch: Partial<AppSettings>) => Promise<void>; selected: ProjectRecord | null }) {
  const [target, setTarget] = useState(''); const [kind, setKind] = useState<'copy' | 'move'>('copy'); const [plan, setPlan] = useState<OperationPlan | null>(null); const [message, setMessage] = useState(''); const [linkSource, setLinkSource] = useState(''); const [linkTarget, setLinkTarget] = useState(''); const [batchSource, setBatchSource] = useState(''); const [batchTarget, setBatchTarget] = useState(''); const [importPath, setImportPath] = useState(''); const [importTitle, setImportTitle] = useState(''); const [importMode, setImportMode] = useState<'copy' | 'move' | 'link'>('link');
  const preview = async () => { if (!selected || !target) return; const next = await window.remake.operations.preview({ kind, source: selected.rootPath, target }); setPlan(next); setMessage(`${next.conflicts.length ? '发现目标冲突' : '预检通过'} · ${fmtSize(next.estimatedBytes)} · ${next.checks.enoughSpace ? '空间充足' : '空间不足'}`); };
  const execute = async () => { if (!plan) return; const conflict = plan.conflicts.length ? prompt('目标已存在：输入 overwrite、rename 或 skip', 'rename') : 'skip'; if (!['overwrite', 'rename', 'skip'].includes(conflict || '')) return; const result = await window.remake.operations.execute(plan, { [plan.target]: conflict as 'overwrite' | 'rename' | 'skip' }); setMessage(result.message); if (result.success) setPlan(null); };
  const addTemp = async () => { const value = await window.remake.settings.pickDirectory(); if (!value) return; await updateSettings({ tempDirectories: [...settings.tempDirectories, { id: crypto.randomUUID(), name: value.split(/[\\/]/).pop() || '临时目录', kind: 'temp', path: value, enabled: true }] }); };
  const importFile = async () => { if (!importPath || !settings.backupPath || !importTitle) return; const project = await window.remake.library.importFile({ inputPath: importPath, managedDirectory: settings.backupPath, title: importTitle, mode: importMode }); setMessage(`已生成项目：${project.title}`); };
  return <section className="tool-panel"><div className="panel-intro"><HardDrive size={20} /><div><h2>存储整理</h2><p>所有迁移都会先预检、暂存并校验，成功后才提交。</p></div></div><div className="storage-layout"><div className="storage-card"><h3>项目迁移</h3><div className="segmented"><button className={kind === 'copy' ? 'active' : ''} onClick={() => setKind('copy')}>复制</button><button className={kind === 'move' ? 'active' : ''} onClick={() => setKind('move')}>移动</button></div><input value={target} onChange={(e) => { setTarget(e.target.value); setPlan(null); }} placeholder={selected ? '输入完整目标路径' : '先从壁纸库选择项目'} disabled={!selected} /><button className="primary-button" onClick={() => void (plan ? execute() : preview())} disabled={!selected || !target}>{plan ? '确认执行' : '预检迁移'}</button>{message && <div className="notice"><Check size={15} />{message}</div>}</div><div className="storage-card"><h3>临时目录</h3><button className="ghost-button full" onClick={() => void addTemp()}>新增目录</button>{settings.tempDirectories.map((source) => <div className="source-line" key={source.id}><span title={source.path}>{source.name}</span><button className={source.enabled ? 'switch on' : 'switch'} onClick={() => void updateSettings({ tempDirectories: settings.tempDirectories.map((item) => item.id === source.id ? { ...item, enabled: !item.enabled } : item) })}><i /></button></div>)}</div><div className="storage-card"><h3>目录符号链接</h3><input value={linkSource} onChange={(e) => setLinkSource(e.target.value)} placeholder="原目录" /><input value={linkTarget} onChange={(e) => setLinkTarget(e.target.value)} placeholder="空目标目录" /><button className="primary-button" onClick={async () => setMessage((await window.remake.storage.createSymlink(linkSource, linkTarget)).message)} disabled={!linkSource || !linkTarget}>创建并保留备份</button></div><div className="storage-card"><h3>批量快捷方式</h3><input value={batchSource} onChange={(e) => setBatchSource(e.target.value)} placeholder="项目源目录" /><input value={batchTarget} onChange={(e) => setBatchTarget(e.target.value)} placeholder="快捷方式输出目录" /><button className="primary-button" onClick={async () => { const rows = await window.remake.storage.createShortcutBatch(batchSource, batchTarget); setMessage(`已处理 ${rows.length} 个快捷方式`); }} disabled={!batchSource || !batchTarget}>批量生成</button></div><div className="storage-card import-card"><h3>单文件生成项目</h3><input value={importPath} onChange={(e) => setImportPath(e.target.value)} placeholder="视频、游戏或程序文件" /><input value={importTitle} onChange={(e) => setImportTitle(e.target.value)} placeholder="项目标题" /><select value={importMode} onChange={(e) => setImportMode(e.target.value as typeof importMode)}><option value="link">保留原位并创建链接</option><option value="copy">复制到项目</option><option value="move">移动到项目</option></select><button className="primary-button" onClick={() => void importFile()} disabled={!importPath || !importTitle || !settings.backupPath}>生成项目</button></div></div></section>;
}
function SettingsPanel({ settings, updateSettings }: { settings: AppSettings; updateSettings: (patch: Partial<AppSettings>) => Promise<void> }) { const [steam, setSteam] = useState(settings.steamPath); const [wallpaper, setWallpaper] = useState(settings.wallpaperPath); const [backup, setBackup] = useState(settings.backupPath); const save = () => void updateSettings({ steamPath: steam, wallpaperPath: wallpaper, backupPath: backup }); const detect = async () => { const found = await window.remake.settings.detectPaths(); setSteam(found.steamPath || ''); setWallpaper(found.wallpaperPath || ''); setBackup(found.backupPath || ''); }; const choose = async (current: string, setter: (value: string) => void) => { const value = await window.remake.settings.pickDirectory(current); if (value) setter(value); }; return <section className="tool-panel settings-panel"><div className="panel-intro"><Settings2 size={20} /><div><h2>工作区设置</h2><p>重制版使用独立配置，不会读取或覆盖旧版 config.json。</p></div></div><div className="settings-form"><button className="ghost-button detect-button" onClick={() => void detect()}><RefreshCw size={15} />从注册表自动识别</button><label>Steam 路径<div className="input-action"><input value={steam} onChange={(e) => setSteam(e.target.value)} placeholder="C:\\Program Files (x86)\\Steam" /><button className="icon-button" onClick={() => void choose(steam, setSteam)}><FolderOpen size={15} /></button></div></label><label>Wallpaper Engine 路径<div className="input-action"><input value={wallpaper} onChange={(e) => setWallpaper(e.target.value)} placeholder="Steam\\steamapps\\common\\wallpaper_engine" /><button className="icon-button" onClick={() => void choose(wallpaper, setWallpaper)}><FolderOpen size={15} /></button></div></label><label>备份路径<div className="input-action"><input value={backup} onChange={(e) => setBackup(e.target.value)} placeholder="projects\\backup" /><button className="icon-button" onClick={() => void choose(backup, setBackup)}><FolderOpen size={15} /></button></div></label><button className="primary-button" onClick={save}><Check size={15} />保存设置</button></div><div className="settings-footer"><button className="ghost-button" onClick={async () => { if (confirm('这会清空重制版设置，但不会影响旧版配置。')) { const next = await window.remake.settings.reset(); setSteam(next.steamPath); setWallpaper(next.wallpaperPath); setBackup(next.backupPath); } }}>重置设置</button><span>配置版本 v{settings.version}</span></div></section>; }
function TaskLog({ events }: { events: TaskEvent[] }) { return events.length ? <div className="task-log"><h3>最近任务</h3>{events.map((event) => <div className="task-row" key={event.taskId}><span>{event.message || event.status}</span><b>{event.progress}%</b></div>)}</div> : null; }

createRoot(document.getElementById('root')!).render(<App />);
