/** Electron entrypoint: wires typed IPC handlers to filesystem, database and task services. */
import { app, BrowserWindow, dialog, ipcMain, shell } from 'electron';
import path from 'node:path';
import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';
import { SettingsStore } from './settings.js';
import { LibraryDatabase } from './database.js';
import { calculatePathSize, scanFolderTree, scanSources } from './scanner.js';
import { cancelOperation, executeOperation, previewOperation, createShortcut, createSymlink, restoreSymlink } from './operations.js';
import { RepkgService } from './repkg.js';
import { importSingleFile } from './importer.js';
import type { AppSettings, FilterState, ProjectRecord, ProjectSource, SourceConfig } from '../src/shared/types.js';

let window: BrowserWindow; let settings: SettingsStore; let database: LibraryDatabase; let repkg: RepkgService;
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const execFileAsync = promisify(execFile);
const emit = (event: Parameters<NonNullable<BrowserWindow['webContents']['send']>>[1]) => window?.webContents.send('task.event', event);
function directoryOf(value: string): string { return path.extname(value) ? path.dirname(value) : value; }
function buildSources(data: AppSettings): SourceConfig[] { const configured = data.sources.filter((item) => item.enabled); const paths: SourceConfig[] = []; const steamRoot = directoryOf(data.steamPath); const wallpaperRoot = directoryOf(data.wallpaperPath); if (steamRoot) paths.push({ ...SettingsStore.source('workshop-default', '创意工坊', 'workshop', path.join(steamRoot, 'steamapps/workshop/content/431960')), metadataFile: wallpaperRoot ? path.join(wallpaperRoot, 'bin/workshopcache.json') : undefined }); if (data.backupPath) paths.push(SettingsStore.source('backup-default', '本地备份', 'backup', data.backupPath)); return [...paths, ...data.tempDirectories.filter((item) => item.enabled), ...configured]; }
function filtered(items: ProjectRecord[], filter: FilterState) { const query = filter.search.trim().toLowerCase(); const folderRefs = filter.folderId ? database.getFolderRefs(filter.folderId) : []; const rows = items.filter((item) => (!query || `${item.title} ${item.workshopId} ${item.description}`.toLowerCase().includes(query)) && (!filter.sources.length || filter.sources.includes(item.source)) && (!filter.types.length || filter.types.includes(item.type)) && (filter.showInvalid || !item.invalid) && (!filter.folderId || folderRefs.some((ref) => ref === item.workshopId || path.normalize(ref).includes(path.normalize(item.rootPath))))); rows.sort((a, b) => { const av = a[filter.sort]; const bv = b[filter.sort]; const result = av < bv ? -1 : av > bv ? 1 : 0; return filter.descending ? -result : result; }); return rows; }
async function registryValue(key: string, name: string): Promise<string> { try { const { stdout } = await execFileAsync('reg.exe', ['query', key, '/v', name], { windowsHide: true }); return stdout.split(/\r?\n/).map((line) => line.trim()).find((line) => line.startsWith(name))?.split(/REG_\w+\s+/)[1]?.trim() || ''; } catch { return ''; } }
function registerIpc() {
  ipcMain.handle('settings.get', () => settings.get()); ipcMain.handle('settings.update', (_e, patch) => settings.update(patch)); ipcMain.handle('settings.reset', async () => { const reset = await settings.reset(); database.reset(); setTimeout(() => { app.relaunch(); app.exit(0); }, 200); return reset; });
  ipcMain.handle('settings.detectPaths', async () => { const steamRoot = await registryValue('HKCU\\Software\\Valve\\Steam', 'SteamPath'); const wallpaperRoot = await registryValue('HKCU\\Software\\WallpaperEngine', 'installPath'); return { steamPath: steamRoot, wallpaperPath: wallpaperRoot, backupPath: wallpaperRoot ? path.join(wallpaperRoot, 'projects', 'backup') : '' }; });
  ipcMain.handle('settings.pickDirectory', async (_e, defaultPath) => { const result = await dialog.showOpenDialog(window, { defaultPath: defaultPath || undefined, properties: ['openDirectory', 'createDirectory'] }); return result.canceled ? null : result.filePaths[0]; });
  ipcMain.handle('settings.pickFile', async (_e, filters) => { const result = await dialog.showOpenDialog(window, { properties: ['openFile'], filters }); return result.canceled ? null : result.filePaths[0]; });
  ipcMain.handle('library.scan', async () => { const taskId = crypto.randomUUID(); void (async () => { const sources = buildSources(settings.get()); database.replaceSources(sources); const rows = await scanSources(sources, (count) => emit({ taskId, kind: 'scan', status: 'running', progress: Math.min(95, count), message: `已扫描 ${count} 个目录` })); database.upsertProjects(rows); const wallpaperRoot = directoryOf(settings.get().wallpaperPath); database.replaceFolders(wallpaperRoot ? await scanFolderTree(path.join(wallpaperRoot, 'config.json')) : []); emit({ taskId, kind: 'scan', status: 'completed', progress: 100, message: `索引 ${rows.length} 个项目` }); })().catch((error) => emit({ taskId, kind: 'scan', status: 'failed', progress: 100, message: String(error) })); return { taskId }; });
  ipcMain.handle('library.list', (_e, query: { filter: FilterState }) => { const rows = filtered(database.list(), query.filter); const start = (query.filter.page - 1) * query.filter.pageSize; return { items: rows.slice(start, start + query.filter.pageSize), total: rows.length, page: query.filter.page, pageCount: Math.max(1, Math.ceil(rows.length / query.filter.pageSize)) }; });
  ipcMain.handle('library.get', (_e, id) => database.get(id)); ipcMain.handle('library.folders', () => database.listFolders()); ipcMain.handle('library.getThumbnail', async (_e, target: string) => { try { const ext = path.extname(target).toLowerCase().slice(1); const mime = ext === 'png' ? 'image/png' : ext === 'gif' ? 'image/gif' : ext === 'webp' ? 'image/webp' : 'image/jpeg'; return `data:${mime};base64,${(await fs.readFile(target)).toString('base64')}`; } catch { return null; } });
  ipcMain.handle('library.updateMetadata', async (_e, id, patch) => { const project = database.get(id); if (!project) throw new Error('项目不存在'); let data: Record<string, unknown> = {}; try { data = JSON.parse(await fs.readFile(project.projectPath, 'utf8')); } catch { /* Missing project.json is repaired when the user explicitly saves metadata. */ } const next = { ...data, title: patch.title, description: patch.description, favorite: patch.favorite, tags: patch.tags, updatedate: Date.now() }; const temporary = `${project.projectPath}.tmp`; await fs.writeFile(temporary, JSON.stringify(next, null, 2), 'utf8'); await fs.rename(temporary, project.projectPath); return database.updateMetadata(id, patch); });
  ipcMain.handle('library.recalculateSize', async (_e, id) => { const project = database.get(id); if (!project) throw new Error('项目不存在'); return database.updateSize(id, await calculatePathSize(project.rootPath)); }); ipcMain.handle('library.importFile', async (_e, request) => { const project = await importSingleFile(request); database.upsertProjects([project]); return project; }); ipcMain.handle('library.openPath', (_e, target) => shell.openPath(target));
  ipcMain.handle('operations.preview', (_e, input) => previewOperation(input)); ipcMain.handle('operations.execute', (_e, plan, actions) => executeOperation(plan, actions, database)); ipcMain.handle('operations.cancel', (_e, id) => cancelOperation(id)); ipcMain.handle('operations.getLog', (_e, id) => database.getOperation(id));
  ipcMain.handle('storage.createSymlink', (_e, source, target) => createSymlink(source, target)); ipcMain.handle('storage.restoreSymlink', (_e, link, backup) => restoreSymlink(link, backup)); ipcMain.handle('storage.createShortcut', (_e, shortcut, target) => createShortcut(shortcut, target)); ipcMain.handle('storage.createShortcutBatch', async (_e, source, target) => { const entries = await fs.readdir(source, { withFileTypes: true }); await fs.mkdir(target, { recursive: true }); return Promise.all(entries.filter((entry) => entry.isDirectory()).map((entry) => createShortcut(path.join(target, `${entry.name}.lnk`), path.join(source, entry.name)))); });
  ipcMain.handle('repkg.start', (_e, input) => repkg.start(input)); ipcMain.handle('repkg.cancel', (_e, id) => repkg.cancel(id)); ipcMain.handle('repkg.getOutput', (_e, id) => repkg.getOutput(id));
  ipcMain.handle('diagnostics.getEnvironment', () => ({ platform: process.platform, arch: process.arch, version: app.getVersion(), userData: app.getPath('userData'), packaged: String(app.isPackaged) }));
}
async function createWindow() { window = new BrowserWindow({ width: 1500, height: 940, minWidth: 1100, minHeight: 700, backgroundColor: '#11151b', webPreferences: { preload: path.join(__dirname, 'preload.cjs'), contextIsolation: true, nodeIntegration: false } }); if (process.argv.includes('--dev')) await window.loadURL('http://localhost:5173'); else await window.loadFile(path.join(__dirname, '../../dist/index.html')); }
app.whenReady().then(async () => { settings = new SettingsStore(); await settings.load(); database = new LibraryDatabase(); repkg = new RepkgService((event) => emit(event)); registerIpc(); await createWindow(); app.on('activate', () => { if (BrowserWindow.getAllWindows().length === 0) void createWindow(); }); });
app.on('window-all-closed', () => { database?.close(); if (process.platform !== 'darwin') app.quit(); });
